# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/base.xdc

# Block Designs: bd/system/system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system}]

# IP: bd/system/ip/system_LEDs_4Bits_1/system_LEDs_4Bits_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_LEDs_4Bits_1 || ORIG_REF_NAME==system_LEDs_4Bits_1}]

# IP: bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_processing_system7_0_0 || ORIG_REF_NAME==system_processing_system7_0_0}]

# IP: bd/system/ip/system_processing_system7_0_axi_periph_2/system_processing_system7_0_axi_periph_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_processing_system7_0_axi_periph_2 || ORIG_REF_NAME==system_processing_system7_0_axi_periph_2}]

# IP: bd/system/ip/system_axi_dma_0_0/system_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_dma_0_0 || ORIG_REF_NAME==system_axi_dma_0_0}]

# IP: bd/system/ip/system_axi_mem_intercon_3/system_axi_mem_intercon_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_mem_intercon_3 || ORIG_REF_NAME==system_axi_mem_intercon_3}]

# IP: bd/system/ip/system_xbar_1/system_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_1 || ORIG_REF_NAME==system_xbar_1}]

# IP: bd/system/ip/system_xbar_0/system_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_0 || ORIG_REF_NAME==system_xbar_0}]

# IP: bd/system/ip/system_system_ila_0_2/system_system_ila_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_system_ila_0_2 || ORIG_REF_NAME==system_system_ila_0_2}]

# Block Designs: bd/system/ip/system_system_ila_0_2/bd_0/bd_1439.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1439 || ORIG_REF_NAME==bd_1439}]

# IP: bd/system/ip/system_system_ila_0_2/bd_0/ip/ip_0/bd_1439_ila_lib_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1439_ila_lib_0 || ORIG_REF_NAME==bd_1439_ila_lib_0}]

# IP: bd/system/ip/system_system_ila_0_2/bd_0/ip/ip_1/bd_1439_g_inst_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1439_g_inst_0 || ORIG_REF_NAME==bd_1439_g_inst_0}]

# IP: bd/system/ip/system_system_ila_0_2/bd_0/ip/ip_2/bd_1439_slot_0_aw_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1439_slot_0_aw_0 || ORIG_REF_NAME==bd_1439_slot_0_aw_0}]

# IP: bd/system/ip/system_system_ila_0_2/bd_0/ip/ip_3/bd_1439_slot_0_w_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1439_slot_0_w_0 || ORIG_REF_NAME==bd_1439_slot_0_w_0}]

# IP: bd/system/ip/system_system_ila_0_2/bd_0/ip/ip_4/bd_1439_slot_0_b_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1439_slot_0_b_0 || ORIG_REF_NAME==bd_1439_slot_0_b_0}]

# IP: bd/system/ip/system_system_ila_0_2/bd_0/ip/ip_5/bd_1439_slot_0_ar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1439_slot_0_ar_0 || ORIG_REF_NAME==bd_1439_slot_0_ar_0}]

# IP: bd/system/ip/system_system_ila_0_2/bd_0/ip/ip_6/bd_1439_slot_0_r_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1439_slot_0_r_0 || ORIG_REF_NAME==bd_1439_slot_0_r_0}]

# IP: bd/system/ip/system_system_ila_0_2/bd_0/ip/ip_7/bd_1439_slot_1_aw_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1439_slot_1_aw_0 || ORIG_REF_NAME==bd_1439_slot_1_aw_0}]

# IP: bd/system/ip/system_system_ila_0_2/bd_0/ip/ip_8/bd_1439_slot_1_w_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1439_slot_1_w_0 || ORIG_REF_NAME==bd_1439_slot_1_w_0}]

# IP: bd/system/ip/system_system_ila_0_2/bd_0/ip/ip_9/bd_1439_slot_1_b_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1439_slot_1_b_0 || ORIG_REF_NAME==bd_1439_slot_1_b_0}]

# IP: bd/system/ip/system_system_ila_0_2/bd_0/ip/ip_10/bd_1439_slot_1_ar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1439_slot_1_ar_0 || ORIG_REF_NAME==bd_1439_slot_1_ar_0}]

# IP: bd/system/ip/system_system_ila_0_2/bd_0/ip/ip_11/bd_1439_slot_1_r_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1439_slot_1_r_0 || ORIG_REF_NAME==bd_1439_slot_1_r_0}]

# IP: bd/system/ip/system_system_ila_0_2/bd_0/ip/ip_12/bd_1439_slot_4_aw_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1439_slot_4_aw_0 || ORIG_REF_NAME==bd_1439_slot_4_aw_0}]

# IP: bd/system/ip/system_system_ila_0_2/bd_0/ip/ip_13/bd_1439_slot_4_w_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1439_slot_4_w_0 || ORIG_REF_NAME==bd_1439_slot_4_w_0}]

# IP: bd/system/ip/system_system_ila_0_2/bd_0/ip/ip_14/bd_1439_slot_4_b_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1439_slot_4_b_0 || ORIG_REF_NAME==bd_1439_slot_4_b_0}]

# IP: bd/system/ip/system_system_ila_0_2/bd_0/ip/ip_15/bd_1439_slot_4_ar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1439_slot_4_ar_0 || ORIG_REF_NAME==bd_1439_slot_4_ar_0}]

# IP: bd/system/ip/system_system_ila_0_2/bd_0/ip/ip_16/bd_1439_slot_4_r_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1439_slot_4_r_0 || ORIG_REF_NAME==bd_1439_slot_4_r_0}]

# IP: bd/system/ip/system_system_ila_0_2/bd_0/ip/ip_17/bd_1439_slot_5_aw_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1439_slot_5_aw_0 || ORIG_REF_NAME==bd_1439_slot_5_aw_0}]

# IP: bd/system/ip/system_system_ila_0_2/bd_0/ip/ip_18/bd_1439_slot_5_w_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1439_slot_5_w_0 || ORIG_REF_NAME==bd_1439_slot_5_w_0}]

# IP: bd/system/ip/system_system_ila_0_2/bd_0/ip/ip_19/bd_1439_slot_5_b_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1439_slot_5_b_0 || ORIG_REF_NAME==bd_1439_slot_5_b_0}]

# IP: bd/system/ip/system_system_ila_0_2/bd_0/ip/ip_20/bd_1439_slot_5_ar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1439_slot_5_ar_0 || ORIG_REF_NAME==bd_1439_slot_5_ar_0}]

# IP: bd/system/ip/system_system_ila_0_2/bd_0/ip/ip_21/bd_1439_slot_5_r_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1439_slot_5_r_0 || ORIG_REF_NAME==bd_1439_slot_5_r_0}]

# IP: bd/system/ip/system_rst_ps7_0_100M_0/system_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rst_ps7_0_100M_0 || ORIG_REF_NAME==system_rst_ps7_0_100M_0}]

# IP: bd/system/ip/system_axis_data_fifo_0_0/system_axis_data_fifo_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axis_data_fifo_0_0 || ORIG_REF_NAME==system_axis_data_fifo_0_0}]

# IP: bd/system/ip/system_xadc_wiz_0_0/system_xadc_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xadc_wiz_0_0 || ORIG_REF_NAME==system_xadc_wiz_0_0}]

# IP: bd/system/ip/system_adc_triger_0_0/system_adc_triger_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_adc_triger_0_0 || ORIG_REF_NAME==system_adc_triger_0_0}]

# IP: bd/system/ip/system_vio_0_0/system_vio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_vio_0_0 || ORIG_REF_NAME==system_vio_0_0}]

# IP: bd/system/ip/system_m02_regslice_0/system_m02_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m02_regslice_0 || ORIG_REF_NAME==system_m02_regslice_0}]

# IP: bd/system/ip/system_m01_regslice_0/system_m01_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m01_regslice_0 || ORIG_REF_NAME==system_m01_regslice_0}]

# IP: bd/system/ip/system_m00_regslice_0/system_m00_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m00_regslice_0 || ORIG_REF_NAME==system_m00_regslice_0}]

# IP: bd/system/ip/system_auto_pc_1/system_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_1 || ORIG_REF_NAME==system_auto_pc_1}]

# IP: bd/system/ip/system_auto_pc_0/system_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_0 || ORIG_REF_NAME==system_auto_pc_0}]

# IP: bd/system/ip/system_auto_us_1/system_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_us_1 || ORIG_REF_NAME==system_auto_us_1}]

# IP: bd/system/ip/system_auto_us_0/system_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_us_0 || ORIG_REF_NAME==system_auto_us_0}]

# XDC: bd/system/ip/system_LEDs_4Bits_1/system_LEDs_4Bits_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_LEDs_4Bits_1 || ORIG_REF_NAME==system_LEDs_4Bits_1}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_LEDs_4Bits_1/system_LEDs_4Bits_1_ooc.xdc

# XDC: bd/system/ip/system_LEDs_4Bits_1/system_LEDs_4Bits_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_LEDs_4Bits_1 || ORIG_REF_NAME==system_LEDs_4Bits_1}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_processing_system7_0_0 || ORIG_REF_NAME==system_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_axi_dma_0_0/system_axi_dma_0_0_ooc.xdc

# XDC: bd/system/ip/system_axi_dma_0_0/system_axi_dma_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_dma_0_0 || ORIG_REF_NAME==system_axi_dma_0_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axi_dma_0_0/system_axi_dma_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_dma_0_0 || ORIG_REF_NAME==system_axi_dma_0_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_xbar_1/system_xbar_1_ooc.xdc

# XDC: bd/system/ip/system_xbar_0/system_xbar_0_ooc.xdc

# XDC: bd/system/ip/system_system_ila_0_2/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1439_ila_lib_0 || ORIG_REF_NAME==bd_1439_ila_lib_0}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_system_ila_0_2/bd_0/ip/ip_0/bd_1439_ila_lib_0_ooc.xdc

# XDC: bd/system/ip/system_system_ila_0_2/bd_0/bd_1439_ooc.xdc

# XDC: bd/system/ip/system_rst_ps7_0_100M_0/system_rst_ps7_0_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rst_ps7_0_100M_0 || ORIG_REF_NAME==system_rst_ps7_0_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_rst_ps7_0_100M_0/system_rst_ps7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rst_ps7_0_100M_0 || ORIG_REF_NAME==system_rst_ps7_0_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_rst_ps7_0_100M_0/system_rst_ps7_0_100M_0_ooc.xdc

# XDC: bd/system/ip/system_axis_data_fifo_0_0/system_axis_data_fifo_0_0_ooc.xdc

# XDC: bd/system/ip/system_axis_data_fifo_0_0/system_axis_data_fifo_0_0/system_axis_data_fifo_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axis_data_fifo_0_0 || ORIG_REF_NAME==system_axis_data_fifo_0_0}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_xadc_wiz_0_0/system_xadc_wiz_0_0_ooc.xdc

# XDC: bd/system/ip/system_xadc_wiz_0_0/system_xadc_wiz_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_xadc_wiz_0_0 || ORIG_REF_NAME==system_xadc_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_vio_0_0/system_vio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_vio_0_0 || ORIG_REF_NAME==system_vio_0_0}]

# XDC: bd/system/ip/system_vio_0_0/system_vio_0_0_ooc.xdc

# XDC: bd/system/ip/system_m02_regslice_0/system_m02_regslice_0_ooc.xdc

# XDC: bd/system/ip/system_m01_regslice_0/system_m01_regslice_0_ooc.xdc

# XDC: bd/system/ip/system_m00_regslice_0/system_m00_regslice_0_ooc.xdc

# XDC: bd/system/ip/system_auto_pc_1/system_auto_pc_1_ooc.xdc

# XDC: bd/system/ip/system_auto_pc_0/system_auto_pc_0_ooc.xdc

# XDC: bd/system/ip/system_auto_us_1/system_auto_us_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_auto_us_1 || ORIG_REF_NAME==system_auto_us_1}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_auto_us_1/system_auto_us_1_ooc.xdc

# XDC: bd/system/ip/system_auto_us_0/system_auto_us_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_auto_us_0 || ORIG_REF_NAME==system_auto_us_0}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_auto_us_0/system_auto_us_0_ooc.xdc

# XDC: bd/system/system_ooc.xdc
