# 
# Synthesis run script generated by Vivado
# 

set_param tcl.collectionResultDisplayLimit 0
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/zybo_base_system3/project_2/project_2.cache/wt [current_project]
set_property parent.project_path E:/zybo_base_system3/project_2/project_2.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths e:/zybo_base_system/source/vivado/hw/lib [current_project]
set_property ip_output_repo e:/zybo_base_system3/project_2/project_2.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib E:/zybo_base_system3/project_2/project_2.srcs/sources_1/bd/system/hdl/system_wrapper.v
add_files E:/zybo_base_system3/project_2/project_2.srcs/sources_1/bd/system/system.bd
set_property used_in_implementation false [get_files -all e:/zybo_base_system3/project_2/project_2.srcs/sources_1/bd/system/ip/system_BTNs_4Bits_0/system_BTNs_4Bits_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/zybo_base_system3/project_2/project_2.srcs/sources_1/bd/system/ip/system_BTNs_4Bits_0/system_BTNs_4Bits_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/zybo_base_system3/project_2/project_2.srcs/sources_1/bd/system/ip/system_BTNs_4Bits_0/system_BTNs_4Bits_0.xdc]
set_property used_in_implementation false [get_files -all e:/zybo_base_system3/project_2/project_2.srcs/sources_1/bd/system/ip/system_LEDs_4Bits_1/system_LEDs_4Bits_1_board.xdc]
set_property used_in_implementation false [get_files -all e:/zybo_base_system3/project_2/project_2.srcs/sources_1/bd/system/ip/system_LEDs_4Bits_1/system_LEDs_4Bits_1_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/zybo_base_system3/project_2/project_2.srcs/sources_1/bd/system/ip/system_LEDs_4Bits_1/system_LEDs_4Bits_1.xdc]
set_property used_in_implementation false [get_files -all e:/zybo_base_system3/project_2/project_2.srcs/sources_1/bd/system/ip/system_SWs_4Bits_2/system_SWs_4Bits_2_board.xdc]
set_property used_in_implementation false [get_files -all e:/zybo_base_system3/project_2/project_2.srcs/sources_1/bd/system/ip/system_SWs_4Bits_2/system_SWs_4Bits_2_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/zybo_base_system3/project_2/project_2.srcs/sources_1/bd/system/ip/system_SWs_4Bits_2/system_SWs_4Bits_2.xdc]
set_property used_in_implementation false [get_files -all e:/zybo_base_system3/project_2/project_2.srcs/sources_1/bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/zybo_base_system3/project_2/project_2.srcs/sources_1/bd/system/ip/system_axi_dma_0_0/system_axi_dma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/zybo_base_system3/project_2/project_2.srcs/sources_1/bd/system/ip/system_axi_dma_0_0/system_axi_dma_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/zybo_base_system3/project_2/project_2.srcs/sources_1/bd/system/ip/system_axi_dma_0_0/system_axi_dma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/zybo_base_system3/project_2/project_2.srcs/sources_1/bd/system/ip/system_xbar_1/system_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/zybo_base_system3/project_2/project_2.srcs/sources_1/bd/system/ip/system_xbar_0/system_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/zybo_base_system3/project_2/project_2.srcs/sources_1/bd/system/ip/system_system_ila_0_2/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all e:/zybo_base_system3/project_2/project_2.srcs/sources_1/bd/system/ip/system_system_ila_0_2/bd_0/ip/ip_0/bd_1439_ila_lib_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/zybo_base_system3/project_2/project_2.srcs/sources_1/bd/system/ip/system_system_ila_0_2/bd_0/bd_1439_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/zybo_base_system3/project_2/project_2.srcs/sources_1/bd/system/ip/system_rst_ps7_0_100M_0/system_rst_ps7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/zybo_base_system3/project_2/project_2.srcs/sources_1/bd/system/ip/system_rst_ps7_0_100M_0/system_rst_ps7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all e:/zybo_base_system3/project_2/project_2.srcs/sources_1/bd/system/ip/system_rst_ps7_0_100M_0/system_rst_ps7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/zybo_base_system3/project_2/project_2.srcs/sources_1/bd/system/ip/system_axis_data_fifo_0_0/system_axis_data_fifo_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/zybo_base_system3/project_2/project_2.srcs/sources_1/bd/system/ip/system_axis_data_fifo_0_0/system_axis_data_fifo_0_0/system_axis_data_fifo_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/zybo_base_system3/project_2/project_2.srcs/sources_1/bd/system/ip/system_m04_regslice_0/system_m04_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/zybo_base_system3/project_2/project_2.srcs/sources_1/bd/system/ip/system_m03_regslice_0/system_m03_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/zybo_base_system3/project_2/project_2.srcs/sources_1/bd/system/ip/system_m02_regslice_0/system_m02_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/zybo_base_system3/project_2/project_2.srcs/sources_1/bd/system/ip/system_m01_regslice_0/system_m01_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/zybo_base_system3/project_2/project_2.srcs/sources_1/bd/system/ip/system_m00_regslice_0/system_m00_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/zybo_base_system3/project_2/project_2.srcs/sources_1/bd/system/ip/system_auto_pc_1/system_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/zybo_base_system3/project_2/project_2.srcs/sources_1/bd/system/ip/system_auto_pc_0/system_auto_pc_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all e:/zybo_base_system3/project_2/project_2.srcs/sources_1/bd/system/ip/system_auto_us_1/system_auto_us_1_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/zybo_base_system3/project_2/project_2.srcs/sources_1/bd/system/ip/system_auto_us_1/system_auto_us_1_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/zybo_base_system3/project_2/project_2.srcs/sources_1/bd/system/ip/system_auto_us_1/system_auto_us_1_ooc.xdc]
set_property used_in_synthesis false [get_files -all e:/zybo_base_system3/project_2/project_2.srcs/sources_1/bd/system/ip/system_auto_us_0/system_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/zybo_base_system3/project_2/project_2.srcs/sources_1/bd/system/ip/system_auto_us_0/system_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/zybo_base_system3/project_2/project_2.srcs/sources_1/bd/system/ip/system_auto_us_0/system_auto_us_0_ooc.xdc]
set_property used_in_implementation false [get_files -all E:/zybo_base_system3/project_2/project_2.srcs/sources_1/bd/system/system_ooc.xdc]
set_property is_locked true [get_files E:/zybo_base_system3/project_2/project_2.srcs/sources_1/bd/system/system.bd]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/zybo_base_system3/project_2/project_2.srcs/constrs_1/new/base.xdc
set_property used_in_implementation false [get_files E:/zybo_base_system3/project_2/project_2.srcs/constrs_1/new/base.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top system_wrapper -part xc7z010clg400-1


write_checkpoint -force -noxdef system_wrapper.dcp

catch { report_utilization -file system_wrapper_utilization_synth.rpt -pb system_wrapper_utilization_synth.pb }
