# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/vivado_hardware_design/xadc_base_design/xadc_base_design.cache/wt [current_project]
set_property parent.project_path E:/vivado_hardware_design/xadc_base_design/xadc_base_design.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
set_property ip_repo_paths d:/hardware/Zybo-XADC-2016.4-1/Zybo-XADC/repo [current_project]
set_property ip_output_repo e:/vivado_hardware_design/xadc_base_design/xadc_base_design.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib E:/vivado_hardware_design/xadc_base_design/xadc_base_design.srcs/sources_1/imports/hdl/XADCdemo.v
read_ip -quiet E:/vivado_hardware_design/xadc_base_design/xadc_base_design.srcs/sources_1/ip/ila_0/ila_0.xci
set_property used_in_implementation false [get_files -all e:/vivado_hardware_design/xadc_base_design/xadc_base_design.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all e:/vivado_hardware_design/xadc_base_design/xadc_base_design.srcs/sources_1/ip/ila_0/ila_0_ooc.xdc]
set_property is_locked true [get_files E:/vivado_hardware_design/xadc_base_design/xadc_base_design.srcs/sources_1/ip/ila_0/ila_0.xci]

read_ip -quiet E:/vivado_hardware_design/xadc_base_design/xadc_base_design.srcs/sources_1/ip/xadc_wiz_0/xadc_wiz_0.xci
set_property used_in_implementation false [get_files -all e:/vivado_hardware_design/xadc_base_design/xadc_base_design.srcs/sources_1/ip/xadc_wiz_0/xadc_wiz_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/vivado_hardware_design/xadc_base_design/xadc_base_design.srcs/sources_1/ip/xadc_wiz_0/xadc_wiz_0.xdc]
set_property is_locked true [get_files E:/vivado_hardware_design/xadc_base_design/xadc_base_design.srcs/sources_1/ip/xadc_wiz_0/xadc_wiz_0.xci]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/vivado_hardware_design/xadc_base_design/xadc_base_design.srcs/constrs_1/imports/constraints/ZYBO_Master.xdc
set_property used_in_implementation false [get_files E:/vivado_hardware_design/xadc_base_design/xadc_base_design.srcs/constrs_1/imports/constraints/ZYBO_Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top XADCdemo -part xc7z010clg400-1 -flatten_hierarchy none -directive RuntimeOptimized -fsm_extraction off


write_checkpoint -force -noxdef XADCdemo.dcp

catch { report_utilization -file XADCdemo_utilization_synth.rpt -pb XADCdemo_utilization_synth.pb }
