vlib work
vlib riviera

vlib riviera/xil_defaultlib
vlib riviera/xpm
vlib riviera/axi_lite_ipif_v3_0_4
vlib riviera/lib_cdc_v1_0_2
vlib riviera/interrupt_control_v3_1_4
vlib riviera/axi_gpio_v2_0_15
vlib riviera/axi_infrastructure_v1_1_0
vlib riviera/xil_common_vip_v1_0_0
vlib riviera/smartconnect_v1_0
vlib riviera/axi_protocol_checker_v1_1_14
vlib riviera/axi_vip_v1_0_2
vlib riviera/axi_vip_v1_0_1
vlib riviera/lib_pkg_v1_0_2
vlib riviera/fifo_generator_v13_1_4
vlib riviera/lib_fifo_v1_0_8
vlib riviera/lib_srl_fifo_v1_0_2
vlib riviera/axi_datamover_v5_1_15
vlib riviera/axi_sg_v4_1_6
vlib riviera/axi_dma_v7_1_14
vlib riviera/generic_baseblocks_v2_1_0
vlib riviera/axi_register_slice_v2_1_13
vlib riviera/axi_data_fifo_v2_1_12
vlib riviera/axi_crossbar_v2_1_14
vlib riviera/gigantic_mux
vlib riviera/xlconcat_v2_1_1
vlib riviera/proc_sys_reset_v5_0_11
vlib riviera/axis_infrastructure_v1_1_0
vlib riviera/axis_data_fifo_v1_1_14
vlib riviera/axi_protocol_converter_v2_1_13
vlib riviera/axi_clock_converter_v2_1_12
vlib riviera/blk_mem_gen_v8_3_6
vlib riviera/axi_dwidth_converter_v2_1_13

vmap xil_defaultlib riviera/xil_defaultlib
vmap xpm riviera/xpm
vmap axi_lite_ipif_v3_0_4 riviera/axi_lite_ipif_v3_0_4
vmap lib_cdc_v1_0_2 riviera/lib_cdc_v1_0_2
vmap interrupt_control_v3_1_4 riviera/interrupt_control_v3_1_4
vmap axi_gpio_v2_0_15 riviera/axi_gpio_v2_0_15
vmap axi_infrastructure_v1_1_0 riviera/axi_infrastructure_v1_1_0
vmap xil_common_vip_v1_0_0 riviera/xil_common_vip_v1_0_0
vmap smartconnect_v1_0 riviera/smartconnect_v1_0
vmap axi_protocol_checker_v1_1_14 riviera/axi_protocol_checker_v1_1_14
vmap axi_vip_v1_0_2 riviera/axi_vip_v1_0_2
vmap axi_vip_v1_0_1 riviera/axi_vip_v1_0_1
vmap lib_pkg_v1_0_2 riviera/lib_pkg_v1_0_2
vmap fifo_generator_v13_1_4 riviera/fifo_generator_v13_1_4
vmap lib_fifo_v1_0_8 riviera/lib_fifo_v1_0_8
vmap lib_srl_fifo_v1_0_2 riviera/lib_srl_fifo_v1_0_2
vmap axi_datamover_v5_1_15 riviera/axi_datamover_v5_1_15
vmap axi_sg_v4_1_6 riviera/axi_sg_v4_1_6
vmap axi_dma_v7_1_14 riviera/axi_dma_v7_1_14
vmap generic_baseblocks_v2_1_0 riviera/generic_baseblocks_v2_1_0
vmap axi_register_slice_v2_1_13 riviera/axi_register_slice_v2_1_13
vmap axi_data_fifo_v2_1_12 riviera/axi_data_fifo_v2_1_12
vmap axi_crossbar_v2_1_14 riviera/axi_crossbar_v2_1_14
vmap gigantic_mux riviera/gigantic_mux
vmap xlconcat_v2_1_1 riviera/xlconcat_v2_1_1
vmap proc_sys_reset_v5_0_11 riviera/proc_sys_reset_v5_0_11
vmap axis_infrastructure_v1_1_0 riviera/axis_infrastructure_v1_1_0
vmap axis_data_fifo_v1_1_14 riviera/axis_data_fifo_v1_1_14
vmap axi_protocol_converter_v2_1_13 riviera/axi_protocol_converter_v2_1_13
vmap axi_clock_converter_v2_1_12 riviera/axi_clock_converter_v2_1_12
vmap blk_mem_gen_v8_3_6 riviera/blk_mem_gen_v8_3_6
vmap axi_dwidth_converter_v2_1_13 riviera/axi_dwidth_converter_v2_1_13

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/7e3a/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/2ad9/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/39ca/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/6eb1/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/1d61/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/acf8/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/d618/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ecd6/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ce23/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/7e3a/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/2ad9/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/39ca/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/6eb1/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/1d61/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/acf8/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/d618/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ecd6/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ce23/hdl/verilog" \
"F:/Xilinx/Vivado/2017.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
"F:/Xilinx/Vivado/2017.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \

vcom -work xpm -93 \
"F:/Xilinx/Vivado/2017.2/data/ip/xpm/xpm_VCOMP.vhd" \

vcom -work axi_lite_ipif_v3_0_4 -93 \
"../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/0ba0/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \

vcom -work lib_cdc_v1_0_2 -93 \
"../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/52cb/hdl/lib_cdc_v1_0_rfs.vhd" \

vcom -work interrupt_control_v3_1_4 -93 \
"../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/e956/hdl/interrupt_control_v3_1_vh_rfs.vhd" \

vcom -work axi_gpio_v2_0_15 -93 \
"../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/cb07/hdl/axi_gpio_v2_0_vh_rfs.vhd" \

vcom -work xil_defaultlib -93 \
"../../../bd/system/ip/system_LEDs_4Bits_1/sim/system_LEDs_4Bits_1.vhd" \

vlog -work axi_infrastructure_v1_1_0  -v2k5 "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/7e3a/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/2ad9/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/39ca/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/6eb1/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/1d61/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/acf8/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/d618/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ecd6/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ce23/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/7e3a/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/2ad9/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/39ca/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/6eb1/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/1d61/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/acf8/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/d618/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ecd6/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ce23/hdl/verilog" \
"../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/7e3a/hdl/axi_infrastructure_v1_1_vl_rfs.v" \

vlog -work xil_common_vip_v1_0_0  -sv2k12 "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/7e3a/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/2ad9/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/39ca/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/6eb1/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/1d61/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/acf8/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/d618/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ecd6/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ce23/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/7e3a/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/2ad9/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/39ca/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/6eb1/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/1d61/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/acf8/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/d618/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ecd6/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ce23/hdl/verilog" \
"../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/2ad9/hdl/xil_common_vip_v1_0_vl_rfs.sv" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/7e3a/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/2ad9/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/39ca/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/6eb1/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/1d61/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/acf8/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/d618/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ecd6/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ce23/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/7e3a/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/2ad9/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/39ca/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/6eb1/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/1d61/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/acf8/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/d618/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ecd6/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ce23/hdl/verilog" \
"../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/39ca/hdl/sc_util_v1_0_vl_rfs.sv" \

vlog -work axi_protocol_checker_v1_1_14  -sv2k12 "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/7e3a/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/2ad9/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/39ca/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/6eb1/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/1d61/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/acf8/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/d618/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ecd6/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ce23/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/7e3a/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/2ad9/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/39ca/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/6eb1/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/1d61/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/acf8/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/d618/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ecd6/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ce23/hdl/verilog" \
"../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/a1b2/hdl/axi_protocol_checker_v1_1_vl_rfs.sv" \

vlog -work axi_vip_v1_0_2  -sv2k12 "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/7e3a/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/2ad9/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/39ca/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/6eb1/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/1d61/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/acf8/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/d618/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ecd6/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ce23/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/7e3a/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/2ad9/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/39ca/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/6eb1/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/1d61/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/acf8/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/d618/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ecd6/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ce23/hdl/verilog" \
"../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/6eb1/hdl/axi_vip_v1_0_vl_rfs.sv" \

vlog -work axi_vip_v1_0_1  -sv2k12 "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/7e3a/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/2ad9/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/39ca/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/6eb1/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/1d61/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/acf8/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/d618/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ecd6/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ce23/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/7e3a/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/2ad9/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/39ca/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/6eb1/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/1d61/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/acf8/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/d618/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ecd6/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ce23/hdl/verilog" \
"../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/1d61/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/7e3a/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/2ad9/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/39ca/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/6eb1/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/1d61/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/acf8/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/d618/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ecd6/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ce23/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/7e3a/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/2ad9/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/39ca/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/6eb1/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/1d61/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/acf8/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/d618/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ecd6/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ce23/hdl/verilog" \
"../../../bd/system/ip/system_processing_system7_0_0/sim/system_processing_system7_0_0.v" \

vcom -work lib_pkg_v1_0_2 -93 \
"../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/832a/hdl/lib_pkg_v1_0_rfs.vhd" \

vlog -work fifo_generator_v13_1_4  -v2k5 "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/7e3a/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/2ad9/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/39ca/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/6eb1/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/1d61/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/acf8/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/d618/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ecd6/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ce23/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/7e3a/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/2ad9/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/39ca/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/6eb1/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/1d61/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/acf8/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/d618/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ecd6/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ce23/hdl/verilog" \
"../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ebc2/simulation/fifo_generator_vlog_beh.v" \

vcom -work fifo_generator_v13_1_4 -93 \
"../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ebc2/hdl/fifo_generator_v13_1_rfs.vhd" \

vlog -work fifo_generator_v13_1_4  -v2k5 "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/7e3a/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/2ad9/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/39ca/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/6eb1/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/1d61/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/acf8/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/d618/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ecd6/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ce23/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/7e3a/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/2ad9/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/39ca/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/6eb1/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/1d61/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/acf8/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/d618/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ecd6/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ce23/hdl/verilog" \
"../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ebc2/hdl/fifo_generator_v13_1_rfs.v" \

vcom -work lib_fifo_v1_0_8 -93 \
"../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/c387/hdl/lib_fifo_v1_0_rfs.vhd" \

vcom -work lib_srl_fifo_v1_0_2 -93 \
"../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/6039/hdl/lib_srl_fifo_v1_0_rfs.vhd" \

vcom -work axi_datamover_v5_1_15 -93 \
"../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/43a6/hdl/axi_datamover_v5_1_vh_rfs.vhd" \

vcom -work axi_sg_v4_1_6 -93 \
"../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ddc9/hdl/axi_sg_v4_1_rfs.vhd" \

vcom -work axi_dma_v7_1_14 -93 \
"../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/bb0b/hdl/axi_dma_v7_1_vh_rfs.vhd" \

vcom -work xil_defaultlib -93 \
"../../../bd/system/ip/system_axi_dma_0_0/sim/system_axi_dma_0_0.vhd" \

vlog -work generic_baseblocks_v2_1_0  -v2k5 "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/7e3a/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/2ad9/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/39ca/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/6eb1/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/1d61/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/acf8/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/d618/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ecd6/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ce23/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/7e3a/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/2ad9/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/39ca/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/6eb1/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/1d61/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/acf8/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/d618/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ecd6/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ce23/hdl/verilog" \
"../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/f9c1/hdl/generic_baseblocks_v2_1_vl_rfs.v" \

vlog -work axi_register_slice_v2_1_13  -v2k5 "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/7e3a/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/2ad9/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/39ca/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/6eb1/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/1d61/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/acf8/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/d618/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ecd6/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ce23/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/7e3a/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/2ad9/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/39ca/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/6eb1/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/1d61/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/acf8/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/d618/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ecd6/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ce23/hdl/verilog" \
"../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/55c0/hdl/axi_register_slice_v2_1_vl_rfs.v" \

vlog -work axi_data_fifo_v2_1_12  -v2k5 "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/7e3a/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/2ad9/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/39ca/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/6eb1/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/1d61/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/acf8/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/d618/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ecd6/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ce23/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/7e3a/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/2ad9/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/39ca/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/6eb1/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/1d61/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/acf8/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/d618/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ecd6/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ce23/hdl/verilog" \
"../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/95b9/hdl/axi_data_fifo_v2_1_vl_rfs.v" \

vlog -work axi_crossbar_v2_1_14  -v2k5 "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/7e3a/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/2ad9/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/39ca/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/6eb1/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/1d61/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/acf8/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/d618/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ecd6/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ce23/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/7e3a/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/2ad9/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/39ca/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/6eb1/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/1d61/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/acf8/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/d618/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ecd6/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ce23/hdl/verilog" \
"../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/f582/hdl/axi_crossbar_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/7e3a/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/2ad9/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/39ca/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/6eb1/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/1d61/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/acf8/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/d618/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ecd6/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ce23/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/7e3a/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/2ad9/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/39ca/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/6eb1/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/1d61/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/acf8/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/d618/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ecd6/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ce23/hdl/verilog" \
"../../../bd/system/ip/system_xbar_1/sim/system_xbar_1.v" \
"../../../bd/system/ip/system_xbar_0/sim/system_xbar_0.v" \
"../../../bd/system/ip/system_system_ila_0_2/bd_0/hdl/bd_1439.v" \
"../../../bd/system/ip/system_system_ila_0_2/bd_0/ip/ip_0/sim/bd_1439_ila_lib_0.v" \

vlog -work gigantic_mux  -v2k5 "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/7e3a/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/2ad9/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/39ca/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/6eb1/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/1d61/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/acf8/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/d618/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ecd6/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ce23/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/7e3a/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/2ad9/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/39ca/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/6eb1/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/1d61/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/acf8/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/d618/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ecd6/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ce23/hdl/verilog" \
"../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/c0d4/hdl/gigantic_mux_v1_0_cntr.v" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/7e3a/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/2ad9/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/39ca/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/6eb1/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/1d61/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/acf8/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/d618/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ecd6/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ce23/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/7e3a/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/2ad9/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/39ca/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/6eb1/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/1d61/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/acf8/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/d618/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ecd6/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ce23/hdl/verilog" \
"../../../bd/system/ip/system_system_ila_0_2/bd_0/ip/ip_1/bd_1439_g_inst_0_gigantic_mux.v" \
"../../../bd/system/ip/system_system_ila_0_2/bd_0/ip/ip_1/sim/bd_1439_g_inst_0.v" \

vlog -work xlconcat_v2_1_1  -v2k5 "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/7e3a/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/2ad9/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/39ca/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/6eb1/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/1d61/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/acf8/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/d618/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ecd6/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ce23/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/7e3a/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/2ad9/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/39ca/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/6eb1/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/1d61/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/acf8/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/d618/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ecd6/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ce23/hdl/verilog" \
"../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/73b7/hdl/xlconcat_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/7e3a/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/2ad9/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/39ca/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/6eb1/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/1d61/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/acf8/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/d618/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ecd6/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ce23/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/7e3a/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/2ad9/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/39ca/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/6eb1/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/1d61/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/acf8/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/d618/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ecd6/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ce23/hdl/verilog" \
"../../../bd/system/ip/system_system_ila_0_2/bd_0/ip/ip_2/sim/bd_1439_slot_0_aw_0.v" \
"../../../bd/system/ip/system_system_ila_0_2/bd_0/ip/ip_3/sim/bd_1439_slot_0_w_0.v" \
"../../../bd/system/ip/system_system_ila_0_2/bd_0/ip/ip_4/sim/bd_1439_slot_0_b_0.v" \
"../../../bd/system/ip/system_system_ila_0_2/bd_0/ip/ip_5/sim/bd_1439_slot_0_ar_0.v" \
"../../../bd/system/ip/system_system_ila_0_2/bd_0/ip/ip_6/sim/bd_1439_slot_0_r_0.v" \
"../../../bd/system/ip/system_system_ila_0_2/bd_0/ip/ip_7/sim/bd_1439_slot_1_aw_0.v" \
"../../../bd/system/ip/system_system_ila_0_2/bd_0/ip/ip_8/sim/bd_1439_slot_1_w_0.v" \
"../../../bd/system/ip/system_system_ila_0_2/bd_0/ip/ip_9/sim/bd_1439_slot_1_b_0.v" \
"../../../bd/system/ip/system_system_ila_0_2/bd_0/ip/ip_10/sim/bd_1439_slot_1_ar_0.v" \
"../../../bd/system/ip/system_system_ila_0_2/bd_0/ip/ip_11/sim/bd_1439_slot_1_r_0.v" \
"../../../bd/system/ip/system_system_ila_0_2/bd_0/ip/ip_12/sim/bd_1439_slot_4_aw_0.v" \
"../../../bd/system/ip/system_system_ila_0_2/bd_0/ip/ip_13/sim/bd_1439_slot_4_w_0.v" \
"../../../bd/system/ip/system_system_ila_0_2/bd_0/ip/ip_14/sim/bd_1439_slot_4_b_0.v" \
"../../../bd/system/ip/system_system_ila_0_2/bd_0/ip/ip_15/sim/bd_1439_slot_4_ar_0.v" \
"../../../bd/system/ip/system_system_ila_0_2/bd_0/ip/ip_16/sim/bd_1439_slot_4_r_0.v" \
"../../../bd/system/ip/system_system_ila_0_2/bd_0/ip/ip_17/sim/bd_1439_slot_5_aw_0.v" \
"../../../bd/system/ip/system_system_ila_0_2/bd_0/ip/ip_18/sim/bd_1439_slot_5_w_0.v" \
"../../../bd/system/ip/system_system_ila_0_2/bd_0/ip/ip_19/sim/bd_1439_slot_5_b_0.v" \
"../../../bd/system/ip/system_system_ila_0_2/bd_0/ip/ip_20/sim/bd_1439_slot_5_ar_0.v" \
"../../../bd/system/ip/system_system_ila_0_2/bd_0/ip/ip_21/sim/bd_1439_slot_5_r_0.v" \
"../../../bd/system/ip/system_system_ila_0_2/sim/system_system_ila_0_2.v" \

vcom -work proc_sys_reset_v5_0_11 -93 \
"../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/5db7/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \

vcom -work xil_defaultlib -93 \
"../../../bd/system/ip/system_rst_ps7_0_100M_0/sim/system_rst_ps7_0_100M_0.vhd" \

vlog -work axis_infrastructure_v1_1_0  -v2k5 "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/7e3a/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/2ad9/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/39ca/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/6eb1/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/1d61/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/acf8/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/d618/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ecd6/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ce23/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/7e3a/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/2ad9/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/39ca/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/6eb1/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/1d61/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/acf8/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/d618/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ecd6/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ce23/hdl/verilog" \
"../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/acf8/hdl/axis_infrastructure_v1_1_vl_rfs.v" \

vlog -work axis_data_fifo_v1_1_14  -v2k5 "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/7e3a/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/2ad9/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/39ca/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/6eb1/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/1d61/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/acf8/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/d618/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ecd6/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ce23/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/7e3a/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/2ad9/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/39ca/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/6eb1/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/1d61/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/acf8/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/d618/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ecd6/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ce23/hdl/verilog" \
"../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/101c/hdl/axis_data_fifo_v1_1_vl_rfs.v" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/7e3a/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/2ad9/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/39ca/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/6eb1/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/1d61/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/acf8/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/d618/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ecd6/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ce23/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/7e3a/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/2ad9/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/39ca/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/6eb1/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/1d61/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/acf8/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/d618/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ecd6/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ce23/hdl/verilog" \
"../../../bd/system/ip/system_axis_data_fifo_0_0/sim/system_axis_data_fifo_0_0.v" \
"../../../bd/system/hdl/system.v" \

vcom -work xil_defaultlib -93 \
"../../../bd/system/ip/system_xadc_wiz_0_0/proc_common_v3_30_a/hdl/src/vhdl/system_xadc_wiz_0_0_conv_funs_pkg.vhd" \
"../../../bd/system/ip/system_xadc_wiz_0_0/proc_common_v3_30_a/hdl/src/vhdl/system_xadc_wiz_0_0_proc_common_pkg.vhd" \
"../../../bd/system/ip/system_xadc_wiz_0_0/proc_common_v3_30_a/hdl/src/vhdl/system_xadc_wiz_0_0_ipif_pkg.vhd" \
"../../../bd/system/ip/system_xadc_wiz_0_0/proc_common_v3_30_a/hdl/src/vhdl/system_xadc_wiz_0_0_family_support.vhd" \
"../../../bd/system/ip/system_xadc_wiz_0_0/proc_common_v3_30_a/hdl/src/vhdl/system_xadc_wiz_0_0_family.vhd" \
"../../../bd/system/ip/system_xadc_wiz_0_0/proc_common_v3_30_a/hdl/src/vhdl/system_xadc_wiz_0_0_soft_reset.vhd" \
"../../../bd/system/ip/system_xadc_wiz_0_0/proc_common_v3_30_a/hdl/src/vhdl/system_xadc_wiz_0_0_pselect_f.vhd" \
"../../../bd/system/ip/system_xadc_wiz_0_0/axi_lite_ipif_v1_01_a/hdl/src/vhdl/system_xadc_wiz_0_0_address_decoder.vhd" \
"../../../bd/system/ip/system_xadc_wiz_0_0/axi_lite_ipif_v1_01_a/hdl/src/vhdl/system_xadc_wiz_0_0_slave_attachment.vhd" \
"../../../bd/system/ip/system_xadc_wiz_0_0/interrupt_control_v2_01_a/hdl/src/vhdl/system_xadc_wiz_0_0_interrupt_control.vhd" \
"../../../bd/system/ip/system_xadc_wiz_0_0/axi_lite_ipif_v1_01_a/hdl/src/vhdl/system_xadc_wiz_0_0_axi_lite_ipif.vhd" \
"../../../bd/system/ip/system_xadc_wiz_0_0/system_xadc_wiz_0_0_drp_arbiter.vhd" \
"../../../bd/system/ip/system_xadc_wiz_0_0/system_xadc_wiz_0_0_drp_to_axi_stream.vhd" \
"../../../bd/system/ip/system_xadc_wiz_0_0/system_xadc_wiz_0_0_xadc_core_drp.vhd" \
"../../../bd/system/ip/system_xadc_wiz_0_0/system_xadc_wiz_0_0_axi_xadc.vhd" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/7e3a/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/2ad9/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/39ca/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/6eb1/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/1d61/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/acf8/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/d618/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ecd6/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ce23/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/7e3a/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/2ad9/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/39ca/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/6eb1/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/1d61/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/acf8/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/d618/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ecd6/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ce23/hdl/verilog" \
"../../../bd/system/ip/system_xadc_wiz_0_0/system_xadc_wiz_0_0.v" \
"../../../bd/system/ip/system_m02_regslice_0/sim/system_m02_regslice_0.v" \
"../../../bd/system/ip/system_m01_regslice_0/sim/system_m01_regslice_0.v" \
"../../../bd/system/ip/system_m00_regslice_0/sim/system_m00_regslice_0.v" \

vlog -work axi_protocol_converter_v2_1_13  -v2k5 "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/7e3a/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/2ad9/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/39ca/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/6eb1/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/1d61/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/acf8/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/d618/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ecd6/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ce23/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/7e3a/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/2ad9/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/39ca/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/6eb1/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/1d61/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/acf8/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/d618/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ecd6/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ce23/hdl/verilog" \
"../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/f0ae/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/7e3a/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/2ad9/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/39ca/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/6eb1/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/1d61/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/acf8/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/d618/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ecd6/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ce23/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/7e3a/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/2ad9/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/39ca/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/6eb1/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/1d61/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/acf8/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/d618/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ecd6/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ce23/hdl/verilog" \
"../../../bd/system/ip/system_auto_pc_1/sim/system_auto_pc_1.v" \
"../../../bd/system/ip/system_auto_pc_0/sim/system_auto_pc_0.v" \

vlog -work axi_clock_converter_v2_1_12  -v2k5 "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/7e3a/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/2ad9/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/39ca/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/6eb1/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/1d61/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/acf8/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/d618/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ecd6/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ce23/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/7e3a/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/2ad9/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/39ca/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/6eb1/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/1d61/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/acf8/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/d618/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ecd6/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ce23/hdl/verilog" \
"../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/80fd/hdl/axi_clock_converter_v2_1_vl_rfs.v" \

vlog -work blk_mem_gen_v8_3_6  -v2k5 "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/7e3a/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/2ad9/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/39ca/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/6eb1/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/1d61/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/acf8/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/d618/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ecd6/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ce23/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/7e3a/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/2ad9/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/39ca/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/6eb1/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/1d61/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/acf8/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/d618/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ecd6/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ce23/hdl/verilog" \
"../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/4158/simulation/blk_mem_gen_v8_3.v" \

vlog -work axi_dwidth_converter_v2_1_13  -v2k5 "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/7e3a/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/2ad9/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/39ca/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/6eb1/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/1d61/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/acf8/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/d618/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ecd6/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ce23/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/7e3a/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/2ad9/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/39ca/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/6eb1/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/1d61/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/acf8/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/d618/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ecd6/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ce23/hdl/verilog" \
"../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/3bde/hdl/axi_dwidth_converter_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/7e3a/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/2ad9/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/39ca/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/6eb1/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/1d61/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/acf8/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/d618/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ecd6/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ce23/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/7e3a/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/2ad9/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/39ca/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/6eb1/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/1d61/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/acf8/hdl" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/d618/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ecd6/hdl/verilog" "+incdir+../../../../xadc_dma.srcs/sources_1/bd/system/ipshared/ce23/hdl/verilog" \
"../../../bd/system/ip/system_auto_us_1/sim/system_auto_us_1.v" \
"../../../bd/system/ip/system_auto_us_0/sim/system_auto_us_0.v" \

vlog -work xil_defaultlib \
"glbl.v"

